# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: diegfern <diegfern@student.42lisboa.com    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/11/22 14:29:06 by diegfern          #+#    #+#              #
#    Updated: 2024/11/22 19:50:13 by diegfern         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

#objetivo:dependencias
#	instrucciones

OBJ = ft_strlen.c mine.c
BINARY = main
CC = cc
CFLAGS = -Wall -Wextra -Werror

main: libft.h $(OBJ)
	cc $(CFLAGS) -o $(BINARY) libft.h $(OBJ)

asd:
	$(CC) $(CFLAGS) $(OBJ) -o aaa.a

